import "../globals.css";
import React from "react";
// import { Inter } from "next/font/google";
import CombinedLayout from "./components/CombinedLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>My Next.js Boilerplate</title>
      </head>
      <body>
        <CombinedLayout>{children}</CombinedLayout>
      </body>
    </html>
  );
}
